<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFramework>$(NetCurrent)</TargetFramework>
		<OutputType>Exe</OutputType>
		<IsPackable>false</IsPackable>
		<DisablePrivateProjectReference>true</DisablePrivateProjectReference>
		<AssemblyName>Uno.UI.Runtime.Skia.Win32.StartupFixture</AssemblyName>
		<RootNamespace>Uno.UI.Runtime.Skia.Win32.StartupFixture</RootNamespace>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\..\..\Uno.UI.Dispatching\Uno.UI.Dispatching.Skia.csproj" />
		<ProjectReference Include="..\..\..\Uno.UI.Runtime.Skia.Win32\Uno.UI.Runtime.Skia.Win32.csproj" />
		<ProjectReference Include="..\..\..\Uno.UI.Runtime.Skia.Win32.Support\Uno.UI.Runtime.Skia.Win32.Support.csproj" />
		<ProjectReference Include="..\..\..\Uno.UWP\Uno.Skia.csproj" />
	</ItemGroup>
</Project>
